# Generated by Django 5.2 on 2025-09-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_zapato_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapato',
            name='imagen',
            field=models.CharField(blank=True, help_text='Ruta en static/images, ej: images/ApacheH1.png', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='zapato',
            name='estado',
            field=models.CharField(choices=[('Pendientes', 'Pendiente'), ('Producción', 'En Producción'), ('Anulado', 'Anulado'), ('Completado', 'Completado'), ('Entregado', 'Entregado'), ('Bodega', 'En Bodega')], default='Pendientes', max_length=10),
        ),
    ]
