# Generated by Django 5.2 on 2025-10-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_zapato_imagen_alter_empleado_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapato',
            name='imagen',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
